### PR TITLE
COMMONSRDF-70: Upgrade Jena version to 3.5.0

### PR DESCRIPTION
**Pull request by ajs6f**

### CODE REVIEW

**Comment by ajs6f** [comment]
Definitely can wait. There's no substantive API changes at stake, and anyone who wants to use Jena 3.5.0 w/ Commons RDF should be able to override the transitive dependency without untoward effect.

**Comment by acoburn** [comment]
In fact, I can confirm that commons-rdf-jena/0.5.0 works fine with jena/3.5.0

**Comment by wikier** [comment]
Now I think this should definitively go in `0.5.0-RC2`.

**Comment by ajs6f** [comment]
👍

**Pull request merged**
